[package]
name = "fdupe"
version = "0.2.0"
authors = ["Fredy Wijaya <fredy.wijaya@gmail.com>"]

[dependencies]
walkdir = "2.4.0"
unicode-segmentation = "1.10.1"
regex = "1.9.6"
clap = { version = "4.4.6", features = ["derive"] }
